name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - run: npm i
      env:
        CI: true

    - run: npm run build
      env:
        BASE_URL: /docs

    - name: Upload to Nexus repository
      env:
        AUTH: ${{ secrets.NEXUS_CREDENTIALS }}
      run: |
        zip -r smart-docs.zip build
        curl $AUTH -T smart-docs.zip "https://repository.smartdust.me/repository/smart-docs.zip"

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
